### ISSUE TITLE
Queue Deployment

### ISSUE THREAD

**Issue by joyguptaa** [Real-Dev-Squad/discord-message-broker#7]
# How to Deploy Queue

## Deployment Overview
The deployment process consists of two main steps:
1. Deploy the Discord Queue with all necessary environment variables.
2. Connect the Queue to the Consumer (i.e., the main.go application).

> Note:
Once the Discord Queue is deployed (e.g., on port XXXX), you will connect the Consumer to that same port.

## Step 1: Discord Queue Setup
The Discord Queue requires a RabbitMQ container. Below is the configuration for the `docker-compose.yml` file to build the RabbitMQ image:
```
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'   # AMQP protocol
      - '15672:15672' # Management UI (optional)

```
This configuration starts a RabbitMQ instance with the necessary ports exposed.

### Prerequisite:
Ensure the Discord Queue (RabbitMQ) is already deployed and running.

### [Required Environment Variables](#env):
1. QUEUE_NAME: Set this to "STAGE_DISCORD_QUEUE".
2. QUEUE_URL: Set this to amqp://<HOST>:<PORT>. If RabbitMQ is running on the default container name (rabbitmq), set it to amqp://rabbitmq:5672.
3. DISCORD_SERVICE_URL : URL of Discord Service

Example `docker-compose.yml` for Consumer:

```
version: '3.8'

services:
  consumer:
    build: .
    container_name: consumer
    depends_on:
      - rabbitmq
    env_file:
      - .env
```

The consumer service depends on `RabbitMQ` and loads environment variables from a .env file, which should include the `QUEUE_NAME` and `QUEUE_URL` value

## Final Step: Verification
Once both services (Queue and Consumer) are deployed, you can verify that by tailing logs of Consumer

That’s it! 🚀 With both images deployed, you should now have a fully functional setup.
